### ISSUE TITLE
Similar idea to MetaL

### ISSUE THREAD

**Issue by jmcastagnetto** [marianoguerra/hiapl#1]
Not sure if you knew about this language, created in the early 2000s by Manuel Lemos (@manuellemos)

https://www.meta-language.net/

**Comment by manuellemos** [comment]
Hello Jesus, good to know that you are alive.

Yes, that is true. I developed MetaL to reduce the cost of developing software by using code generation. Over here at Icontem, the company that manages PHP Classes, we use MetaL and an application called MetaStorage to generate ORM classes to store objects in database tables. I would say that 60% of the PHP Classes site code was generated by MetaStorage.

It seems Mario project is for a different purpose. Lets see how it goes.
